name: PlatinumHaul
main: com.gmail.Annarkwin.Platinum.Haul.Haul
version: 1.0
api-version: 1.16
depend: [PlatinumAPI]

commands:
  BottleExp:
    description: "Fill exp bottles for later use"
    aliases: [bxp]
    permission: platinum.command.bottleexp
    usage: /BottleExp help
  Enchant:
    description: "Enchant items"
    aliases: []
    permission: platinum.command.enchant
    usage: /Enchant help

permissions:
  Platinum.bottleexp.user:
    default: true
    children:
      Platinum.command.bottleexp: true
      Platinum.command.bottleexp.help: true
      Platinum.command.bottleexp.fill: true